local theme_file_path = vim.fn.stdpath("config") .. "/after/plugin/active_theme.lua"

local function write_theme_file(name)
  local f = io.open(theme_file_path, "w")
  if f then
    local header = "-- This file is automatically generated by the colorscheme picker\n"
    local command = string.format('vim.cmd.colorscheme("%s")', name)
    f:write(header .. command)
    f:close()
  end
end

return {
  {
    "folke/snacks.nvim",
    ---@type snacks.Config
    priority = 1000,
    lazy = false,
    opts = {
      --snacks.indent
      indent = {
        animate = { duration = { step = 5 } }
      },
      --snacks.dashboard
      dashboard = {},
      --snacks.terminal
      terminal = {
        stack = true,
        win = {
          position = "bottom",
          height = 0.4,
        }
      },
      --snacks.picker
      picker = {},
    },
    keys = {
      -- Colorscheme Picker (with persistence)
      { "<leader>st", function()
        Snacks.picker.colorschemes({
          confirm = function(picker, item)
            if item then
              picker.preview.state.colorscheme = nil
              vim.cmd.colorscheme(item.text)
              write_theme_file(item.text)
            end
            picker:close()
          end,
        })
      end, desc = "Search Themes" },
      -- General Pickers
      { "<leader>sk", function() Snacks.picker.keymaps() end, desc = "Keymaps" },
      { "<leader><leader>", function() Snacks.picker.buffers() end, desc = "Buffers" },
      { "<leader>sf", function() Snacks.picker.files() end, desc = "Find Files" },
      { "<leader>sg", function() Snacks.picker.grep() end, desc = "Grep (Live)" },

      -- LSP Pickers
      { "gd", function() Snacks.picker.lsp_definitions() end, desc = "Goto Definition" },
      { "gr", function() Snacks.picker.lsp_references() end, desc = "References" },
    },
  },
}
